-- 사용자
CREATE TABLE ACCOUNT(
	ACCOUNT_ID VARCHAR2(20) PRIMARY KEY,
	ACCOUNT_PW VARCHAR2(600) NOT NULL,
	ACCOUNT_NAME VARCHAR2(50) NOT NULL,
	ACCOUNT_PHONE VARCHAR2(20) NOT NULL,
	ACCOUNT_EMAIL VARCHAR2(50) NOT NULL,
	ACCOUNT_CODE NUMBER NOT NULL,
	ACCOUNT_POSITION VARCHAR2(50) NOT NULL,
	AUTH CHAR(1) NOT NULL,
	ACCOUNT_DELFAG CHAR(1) NOT NULL,
	ACCOUNT_REGDATE DATE NOT NULL
);

-- 사용자 등록
INSERT INTO ACCOUNT
(ACCOUNT_ID, ACCOUNT_PW, ACCOUNT_NAME, ACCOUNT_PHONE, ACCOUNT_EMAIL, ACCOUNT_CODE, ACCOUNT_POSITION, AUTH, ACCOUNT_DELFAG, ACCOUNT_REGDATE)
VALUES('iseul', '1234', '문이슬', '010-3333-4444', 'iseul@gmail.com', 100002, '품질관리', 'U', 'N', SYSDATE);

-- 사용자 중복 체크
SELECT ACCOUNT_ID FROM ACCOUNT WHERE ACCOUNT_ID='kimhscom';

-- 로그인
SELECT ACCOUNT_ID, ACCOUNT_PW, ACCOUNT_NAME, ACCOUNT_PHONE, ACCOUNT_EMAIL, ACCOUNT_CODE, ACCOUNT_POSITION, AUTH, ACCOUNT_DELFAG, ACCOUNT_REGDATE
FROM ACCOUNT 
WHERE UPPER(ACCOUNT_ID)=UPPER('kimhscom') AND ACCOUNT_PW='1234' AND ACCOUNT_DELFAG='N';

-- 암호화된 비밀번호 가져오기
SELECT ACCOUNT_PW FROM ACCOUNT WHERE ACCOUNT_ID='kimhscom';

-- 비밀번호 찾기
UPDATE ACCOUNT 
SET ACCOUNT_PW='1234' 
WHERE ACCOUNT_ID='kimhscom' AND ACCOUNT_EMAIL='kimhscom1@icloud.com';

-- 사용자 상세조회
SELECT ACCOUNT_ID, ACCOUNT_PW, ACCOUNT_NAME, ACCOUNT_PHONE, ACCOUNT_EMAIL, ACCOUNT_CODE, ACCOUNT_POSITION, AUTH, ACCOUNT_DELFAG, ACCOUNT_REGDATE
FROM ACCOUNT
WHERE ACCOUNT_ID='kimhscom';

-- 사용자 전체조회(페이징)
SELECT ACCOUNT_ID, ACCOUNT_PW, ACCOUNT_NAME, ACCOUNT_PHONE, ACCOUNT_EMAIL, ACCOUNT_CODE, ACCOUNT_POSITION, AUTH, ACCOUNT_DELFAG, ACCOUNT_REGDATE
FROM 
(SELECT ROWNUM RNUM, ACCOUNT_ID, ACCOUNT_PW, ACCOUNT_NAME, ACCOUNT_PHONE, ACCOUNT_EMAIL, ACCOUNT_CODE, ACCOUNT_POSITION, AUTH, ACCOUNT_DELFAG, ACCOUNT_REGDATE
FROM
(SELECT ACCOUNT_ID, ACCOUNT_PW, ACCOUNT_NAME, ACCOUNT_PHONE, ACCOUNT_EMAIL, ACCOUNT_CODE, ACCOUNT_POSITION, AUTH, ACCOUNT_DELFAG, ACCOUNT_REGDATE
FROM ACCOUNT
ORDER BY ACCOUNT_REGDATE DESC)
)
WHERE RNUM BETWEEN 1 AND 3;

-- 사용자 사용가능 전체조회(페이징)
SELECT ACCOUNT_ID, ACCOUNT_PW, ACCOUNT_NAME, ACCOUNT_PHONE, ACCOUNT_EMAIL, ACCOUNT_CODE, ACCOUNT_POSITION, AUTH, ACCOUNT_DELFAG, ACCOUNT_REGDATE
FROM 
(SELECT ROWNUM RNUM, ACCOUNT_ID, ACCOUNT_PW, ACCOUNT_NAME, ACCOUNT_PHONE, ACCOUNT_EMAIL, ACCOUNT_CODE, ACCOUNT_POSITION, AUTH, ACCOUNT_DELFAG, ACCOUNT_REGDATE
FROM
(SELECT ACCOUNT_ID, ACCOUNT_PW, ACCOUNT_NAME, ACCOUNT_PHONE, ACCOUNT_EMAIL, ACCOUNT_CODE, ACCOUNT_POSITION, AUTH, ACCOUNT_DELFAG, ACCOUNT_REGDATE
FROM ACCOUNT
WHERE ACCOUNT_DELFAG='N' ORDER BY ACCOUNT_REGDATE DESC)
)
WHERE RNUM BETWEEN 1 AND 3;

-- 사용자 총 인원 조회
SELECT COUNT(*) FROM ACCOUNT WHERE ACCOUNT_DELFAG='N';

-- 사용자 정보 수정
UPDATE ACCOUNT 
SET ACCOUNT_PW='2222', ACCOUNT_PHONE='010-5555-6666', ACCOUNT_EMAIL='iseul1@gmail.com', ACCOUNT_POSITION='출하관리'
WHERE ACCOUNT_ID='iseul';

-- 사용자 권한 수정
UPDATE ACCOUNT SET AUTH='U' WHERE ACCOUNT_ID='iseul';

-- 사용자 삭제
UPDATE ACCOUNT SET ACCOUNT_DELFAG='N' WHERE ACCOUNT_ID='iseul';